name: (Runtime) Publish Prereleases Nightly

on:
  schedule:
    # At 10 minutes past 16:00 on Mon, Tue, Wed, Thu, and Fri
    - cron: 10 16 * * 1,2,3,4,5

env:
  TZ: /usr/share/zoneinfo/America/Los_Angeles

jobs:
  publish_prerelease_canary:
    name: Publish to Canary channel
    uses: facebook/react/.github/workflows/runtime_prereleases.yml@main
    with:
      commit_sha: ${{ github.sha }}
      release_channel: stable
      dist_tag: canary,next,rc
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish_prerelease_experimental:
    name: Publish to Experimental channel
    uses: facebook/react/.github/workflows/runtime_prereleases.yml@main
    # NOTE: Intentionally running these jobs sequentially because npm
    # will sometimes fail if you try to concurrently publish two
    # different versions of the same package, even if they use different
    # dist tags.
    needs: publish_prerelease_canary
    with:
      commit_sha: ${{ github.sha }}
      release_channel: experimental
      dist_tag: experimental
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
